# This is a basic workflow to help you get started with Actions

name: Security Audit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0' #Corre todos los domingos a medianoche

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  audit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.54.1/trivy_0.54.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.54.1_Linux-64bit.deb

      - name: Run Security audit
        run: |
           echo "Running security audit"
           trivy fs --exit-code 1 --severity HIGH,CRITICAL .
           echo "Audit complete."

      - name: Storage logs
        uses: actions/upload-artifact@v2
        with:
          name: audit-logs
          path: ./audit-logs
